export const {
  $DOC,
  $WIN,
  $HTMLBODY,
  $HTML,
  $BODY,
  OUT,

  ACTIVE,
  OPEN,
  VISIBLE,
  FOCUS,
  ANIMATE,
  HIDDEN,
  NOSCROLL,
  NOTOUCH,
  ERROR,
  HASTEXT,
  VALID,
  FIXED
} = {
  $DOC: $(document),
  $WIN: $(window),
  $HTMLBODY: $('html, body'),
  $HTML: $('html'),
  $BODY: $('body'),
  OUT: document.querySelector('.out'),

  ACTIVE: 'is-active',
  OPEN: 'is-open',
  VISIBLE: 'is-visible',
  FOCUS: 'has-focus',
  ANIMATE: 'is-animate',
  HIDDEN: 'is-hidden',
  NOSCROLL: 'no-scroll',
  NOTOUCH: 'no-touch',
  ERROR: 'has-error',
  HASTEXT: 'has-text',
  VALID: 'is-valid',
  FIXED: 'is-fixed'
};
